name: Check Markdown links

on: 
  push
  pull_request

jobs:
  markdown-link-check:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run link check 
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quite-mode: 'no'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'no'